require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.theme"
require "user.completion"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comments"
require "user.gitsigns"
require "user.nvim-tree"
-- require "user.bufferline"
